sonar.projectKey=my-local-project
sonar.projectName=Terraform Infra Scan
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.login=sqp_12271d455fa56d63d27fa72339e24a14cfb53bcd
sonar.language=terraform
